services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: n8n_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-n8n}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-n8n}
      POSTGRES_DB: ${POSTGRES_DB:-n8n}
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 3s
      retries: 10

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    container_name: ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: unless-stopped
    container_name: n8n
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_started
    ports:
      - '5678:5678'
    environment:
      # Timezone
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE:-Asia/Jakarta}
      TZ: ${TZ:-Asia/Jakarta}

      N8N_HOST: ${N8N_HOST:-localhost}
      N8N_PORT: ${N8N_PORT:-5678}
      N8N_PROTOCOL: ${N8N_PROTOCOL:-http}
      # WEBHOOK_URL: ${WEBHOOK_URL:-http://localhost:5678/}

      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB:-n8n}
      DB_POSTGRESDB_USER: ${POSTGRES_USER:-n8n}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD:-n8n}
      DB_POSTGRESDB_SCHEMA: ${POSTGRES_SCHEMA:-public}

      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: 'true'
      N8N_RUNNERS_ENABLED: 'true'
      # N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY:-}

    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  pg_data:
  n8n_data:
  ollama_data:
